### ISSUE TITLE
The reason for using two datasets together? 

### ISSUE THREAD

**Issue by suzy027a** [tonyduan/hte-prediction-rcts#1]
Hi Tony,

Thank you for sharing the code publicly. I read the paper and I am wondering if there are any specific reasons for using these two ACCORD and SPRINT datasets together, especially for the sensitivity analysis part, the result for using only one dataset is not as good as the combined one. So, how to ensure the generability?

Thank you very much.

Suxi

**Comment by tonyduan** [comment]
Thanks for reaching out.

The primary reason we wanted to combine the two datasets together was to improve the amount of training data available, as the combination of SPRINT (N=9361) and ACCORD BP (N=4733) yielded significantly more patients. A secondary reason was to explore to what degree the method could show the positive ARR in SPRINT and null result in ACCORD BP **(Supplemental Figure 5)**.

<img width="285" alt="Screen Shot 2019-04-11 at 12 54 58 AM" src="https://user-images.githubusercontent.com/1163598/55940403-e6923480-5bf4-11e9-9285-dc6c928a6037.png">

Please don't hesitate to reach out with further questions.

**Comment by suzy027a** [comment]
Hi Tony,

Thanks for the detailed explanation. 

Suxi
